DROP TABLE IF EXISTS ACCOUNT;

CREATE TABLE IF NOT EXISTS ACCOUNT
(
    ACCOUNT_ID VARCHAR(81) NOT NULL,
    NAME VARCHAR(40) NOT NULL,
    EMAIL VARCHAR(40) NOT NULL,
    BALANCE INT DEFAULT 0,
    CREATED_TMST TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_TMST TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(ACCOUNT_ID)
);